# default-config.yaml

goes_first: player_a  # player_a, player_b, random

player_a:
  deckPath: decks/UWTempo.dck
  type: mcts
  output_dir: data/playerA


  priors:
    priority: false
    target: false
    binary: false
    opponent: false

  noise:
    enabled: false

  mcts:
    search_budget: 1000
    timeout_ms: 4000
    td_discount: 0.95

  mulligans:
    enabled: False

  hidden_info:
    see_opponent_hand: True

player_b:
  deckPath: decks/Standard-MonoW.dck
  type: minimax
  output_dir: data/playerB

  priors:
    priority: false
    target: false
    binary: false
    opponent: false

  noise:
    enabled: false

  mcts:
    search_budget: 1000
    timeout_ms: 4000
    td_discount: 0.95

  mulligans:
    enabled: false

  hidden_info:
    see_opponent_hand: True

training:
  games: 200
  threads: 4
  max_turns: 50 #does nothing

server:
  host: localhost
  port: 50052
  opponent_port: 50053

logging:
  log_feature_hash: False
  save_final_wr: true
  show_wr: true #does nothing