# default-config.yaml

goes_first: player_a  # player_a, player_b, random

player_a:
  deckPath: decks/UWTempo.dck
  type: mcts
  output_dir: data/playerA

  priors:
    priority: true
    target: false
    binary: true
    opponent: false
    prior_temperature: 1.5 #does nothing

  noise:
    enabled: false
    dirichlet_noise: 0.15 #does nothing
    selection_temperature: 2 #does nothing

  mcts:
    search_budget: 1000
    timeout_ms: 4000
    td_discount: 0.95
    offline_mode: false

  gameplay:
    mulligans_enabled: false
    manual_tapping: true


  hidden_info:
    see_opponent_hand: true

player_b:
  deckPath: decks/Standard-MonoR.dck
  type: minimax
  output_dir: data/playerB

  priors:
    priority: false
    target: false
    binary: false
    opponent: false
    prior_temperature: 1.5 #does nothing

  noise:
    enabled: false
    dirichlet_noise: 0.15 #does nothing
    selection_temperature: 2 #does nothing

  mcts:
    search_budget: 1000
    timeout_ms: 4000
    td_discount: 0.95
    offline_mode: false

  gameplay:
    mulligans_enabled: false
    manual_tapping: true


  hidden_info:
    see_opponent_hand: true

training:
  games: 200
  threads: 4
  max_turns: 50 #does nothing

server:
  host: localhost
  port: 50052
  opponent_port: 50053

logging:
  sparse: false #does nothing
  all_threads: true
  log_feature_hash: false
  save_final_wr: true
  show_mcts_info: true #does nothing
